### ISSUE TITLE
AI Configurability

### ISSUE THREAD

**Issue by RobotSail** [redhat-et/copilot-ops#11]
Enable the user to configure the AI module's parameters, including which backend to be using. 

OpenAI currently supports the following parameters per API call: [Completion API docs](https://beta.openai.com/docs/api-reference/completions/create
)

**Comment by RobotSail** [comment]
@guymguym This could be related to the `copilot-ops.yaml` we're using for configurations.

**Comment by guymguym** [comment]
@RobotSail Yes - can we already define this configurations structure? or is it still unknown? If you have any known variables we want to support we can add it to the [Config struct](https://github.com/redhat-et/copilot-ops/blob/992ff8ecd9afc47c96f528a5c0c6d2d01666d534/pkg/cmd/config.go#L11-L14)
