### ISSUE TITLE
Default Path For Newly-Generated Files

### ISSUE THREAD

**Issue by RobotSail** [redhat-et/copilot-ops#23]
When generating new files, it'll always be a guessing game for the CLI as to where newly-generated files should be saved to.
There are a few solutions to this:
- default / user-specified output directory
- attempting to extract generated metadata to infer where file should be saved to, based on defined `.copilot-ops.yml`
- user-specified commands within the content describing where the requested generated files should be saved to

**Comment by RobotSail** [comment]
@guymguym Is this something that Filesets could solve? I.e. having a `defaultPath` attribute for each entry?

**Comment by guymguym** [comment]
@RobotSail Sure - that's an easy way to add such a property

**Comment by guymguym** [comment]
We decide to just set the new name to "generated-by-copilot-ops" and let the user/bot change it. Will revise if needed in the future.
