### ISSUE TITLE
Wrong key variable name in README.md

### ISSUE THREAD

**Issue by dmartinol** [redhat-et/copilot-ops#42]
The variable name is described as OPENAI_API_TOKEN in the README.md, but actually it is OPENAI_API_KEY.

**Comment by guymguym** [comment]
@dmartinol @RobotSail @cooktheryan 
I think we can set up a github workflow on this repo that whenever I type /copilot-ops in a comment it runs the cli and creates a PR referencing that comment, and then we can resolve this issue by typing:

```
/copilot-ops edit README.md -- replace all OPENAI_API_TOKEN with OPENAI_API_KEY 
```

:)
https://pakstech.com/blog/gh-actions-issue-comments/
https://github.community/t/how-to-use-the-github-actions-bot/16535/2

**Comment by guymguym** [comment]
ok we have an initial bot, so lets try this:

/copilot-ops edit --file README.md --request "The variable name is described as OPENAI_API_TOKEN in the README.md, but actually it is OPENAI_API_KEY"
