### ISSUE TITLE
Setup CI Build process

### ISSUE THREAD

**Issue by RobotSail** [redhat-et/copilot-ops#49]
We need to create an automated build process which runs `make build` on new tags and nightly builds so that `copilot-ops` can be consumed without cloning the repository and running `make build`.

**Comment by guymguym** [comment]
We seem to have it in [ci.yaml](https://github.com/redhat-et/copilot-ops/blob/main/.github/workflows/ci.yaml), It runs on PR, tags or push to main, and uploads the binaries as artifacts, see [last build](https://github.com/redhat-et/copilot-ops/actions/runs/2411818312) for example. Is there something missing?
