### ISSUE TITLE
Hosting copilot-ops as a service, hiding AI engine subscription internally

### ISSUE THREAD

**Issue by RobotSail** [redhat-et/copilot-ops#79]
We would like copilot-ops to be offered as a managed service, something that can be productized in the future.
This includes user authentication and management, providing the service to OpenShift, RHEL users, along with as a GitHub bot that has its own pricing model.

**Comment by RobotSail** [comment]
Ideas:
- Having RHEL provides you with some credit with using copilot-ops

**Comment by guymguym** [comment]
closing in favor of the bot repo - https://github.com/redhat-et/copilot-ops-bot
